export const BREAKING_NEWS = [
  'Man still exists',
  'Clouds remain above ground',
  'Tuesday confirmed',
  'Water reported wet again',
  'Local void continues to stare back',
  'Scientists discover sky still there',
  'Gravity persists for third consecutive year',
  'Area cat indifferent to everything',
  'Experts agree: something is happening',
  'Breaking: nothing has changed',
  'Exclusive: this sentence contains words',
  'Time continues to move forward',
  'Beige energy detected in tri-state area',
  'Man unsure if he blinked or universe reset',
  'Socks report mixed results',
  'Local ceiling unchanged, sources confirm',
  'Sandwich status: probably fine',
  'Scientists confirm: Monday follows Sunday',
  'Someone somewhere is eating cereal right now',
  'The algorithm is doing something, officials say',
  'Experts weigh in: yes',
  'Report: chair still a chair',
  'Mid-afternoon energy: uncertain',
  'Breaking: the concept of later still exists',
  'Sources close to toast report: bread was involved',
  'Trees remain mostly stationary',
  'Update: nothing has been resolved',
  'Flash: a pigeon',
  'Clock found doing clock things',
  'New study confirms: soup is wet',
  'Officials release statement: ok',
  'Strange beeping sound explained as beeping',
  'Witness says she "just saw a thing"',
  'Temperatures reported as a number',
]

export const SCORE_REASONS = [
  'mercury is in retrograde',
  'a cat somewhere sneezed',
  'the algorithm felt like it',
  'you breathed',
  'the void giggled',
  'someone ate cereal for dinner',
  'a pigeon looked at a building',
  'Tuesday happened again',
  'the server hiccuped',
  'a dog barked at nothing',
  'the moon shrugged',
  'quantum uncertainty increased briefly',
  'a butterfly flapped in Ohio',
  'someone used Comic Sans unironically',
  'the sun was a bit round today',
  'gravity persisted as usual',
  'a sock was lost in a dryer',
  'someone thought about sandwiches',
  'the universe blinked',
  'a cloud changed shape for no reason',
  'someone said "per my last email"',
  'a star somewhere is confused',
  'someone left a cupboard open',
  'an algorithm had feelings',
  'existing is expensive',
  'the vibes shifted at 3:47am',
  'a tree made a sound and nobody heard it',
  'your aura was recalibrated automatically',
  'someone nearby thought very loudly',
  'the internet gods are bored',
  'entropy increased, as always',
  'you were in the wrong timezone mentally',
  'the algorithm sneezed',
  'a number wanted to change',
]

export const GLOBAL_VIBES = ['chaotic', 'moist', 'beige', 'uncertain', 'crispy', 'clammy', 'oblique', 'pending', 'damp', 'fluorescent']

export const REACTION_LABELS = ['vibe it', 'blorped', 'felt that', 'ok???', 'certified', 'witnessed', 'processed', 'absorbed', '✓ real']
